version: '3.8'

services:
  db:
    container_name: database_app
    image: postgres:15
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env